### PR TITLE
small modification to get youtube video name via youtube v3 api. need…

### PR DESCRIPTION
**Pull request by scott-davidjones**
Added a quick change to pull video name from YouTube API v3. Does require a valid api key from console.developers.google.com.

Signed-off-by: Scott Jones Scott.Jones@AutumnDev.co.uk

### CODE REVIEW

**Comment by smhmic** [comment]
Nice add!  But, this method can be unreliable on bigger sites, as the API has a quota.  This should cache the video title at least for the current page.

If this were to go into this script, I think that API limitation should be noted in the description, to make the user aware before they decide to activate this option.

**Comment by scott-davidjones** [comment]
ok will see about adding caching for the current page in the form of jquery $.cache. Do you have any objections to the use of jQuery?

**Comment by scott-davidjones** [comment]
hmm by default it looks like the $.get() should cache the request and responses. will add the info into the read me though.

**Comment by DanWilkerson** [comment]
Hi Scott,

I really appreciate the contribution, but I won't be merging it with the repo; I'm concerned about users ignoring or being unaware of the API limit. I appreciate that your changes won't force usage of the API, but we don't want to support it on this particular project; sorry, it's just a design decision we made early on. I would strongly encourage you to fork the repo and include your changes there, though! I'd be happy to shout out your fork in the README file, for users who do want to use the API.

Dan

**Pull request closed without merging**
