### PR TITLE
Fix event binding failing silently if triggered before player loads

### PR DESCRIPTION
**Pull request by Scott-MacD**
In the current implementation, if the analytics script runs before the youtube video has loaded, the player will never fire any change events, and therefore will never be logged in analytics without any sort of errors. This adds a simple check to make sure the player API is available before binding to it and adding the `youTubeIframe.pauseFlag`.

### CODE REVIEW

**Comment by DanWilkerson** [comment]
Can you share a plnkr that reproduces this issue? This doesn't sound correct to me; players operate independently of the content they load and should still emit change events even if they're bound before the video itself has finished loading, and none of this is called unless the YouTube Iframe API is loaded.

**Comment by Scott-MacD** [comment]
No problem, I'll try to toss one together later this evening.

In the mean time here's a more detailed explanation that you can check for yourself by setting a break point on the same line as that if statement. It looks like it's probably a race condition, however if the script triggers before youtube does, and you inspect the "player" object, there is an extremely limited subset of the API available. Once the video actually **does** load, then your script triggers again and creates a new player, this time with the appropriate API and permissions, however the `pauseFlag` is set to false from the previous time it was triggered, and therefor doesn't bind the event listeners to this new instance of player (which is the correct one).

I'll try to find time this evening to set up a plnkr and shared analytics verifying the bug and fix.

**Comment by Scott-MacD** [comment]
Also, I should clarify, the youtube API is available, but rather the specific methods available on the player instance are different depending on whether it has loaded or not. My assumption is this is some sort of permission thing to mitigate XSS that may have changed in the last couple years.

**Comment by DanWilkerson** [comment]
I believe I've seen this before when an old Javascript API is loaded, [which was deprecated a few years back](https://youtube-eng.googleblog.com/2015/01/youtube-now-defaults-to-html5_27.html). Check that the page doesn't include this script anywhere:

https://www.youtube.com/player_api

**Comment by Scott-MacD** [comment]
Indeed that script does appear to be getting added to the page, I'll look into why. Literally the only thing I have on that page at all is the youtube embed iframe (by clicking "share" on youtube, just this morning), the Google Analytics snippit, and your JS file taken from this repo.

**Comment by DanWilkerson** [comment]
It should work once that's removed. LMK if otherwise!

**Comment by Scott-MacD** [comment]
Well, as mentioned, I don't have it in the page, it's getting dynamically added, I'm guessing by the youtube embed? I'm debugging right now, but here's the page it's on if you're curious:
http://thework.brandhealth.ca/

As mentioned, extremely minimal page.

**Comment by Scott-MacD** [comment]
No, I made a mistake here. The embed script is loading `iframe_api`, not `player_api`. I misread.

**Comment by DanWilkerson** [comment]
I don't see https://www.youtube.com/player_api loading on that page and I do see the dataLayer events coming through - I also see the player complaining about the origin parameter, which is weird.

**Comment by Scott-MacD** [comment]
This one is working with my fix implemented. I'll upload a new copy somewhere with the broken script.

**Comment by DanWilkerson** [comment]
I found the issue - the script is changing the protocol of the src attribute of the iframe to match that of the window loading the video, which is.. not great. I'll put a fix in.

**Comment by DanWilkerson** [comment]
I should add that there's native support for YT video tracking in GTM now, which is often a better choice. LMK if it still seems wrong on your end.

**Comment by DanWilkerson** [comment]
Missed that your version had your fix, too. I tested it with fix in place (hurray for Local Overrides!) and it seemed to be all good. I'll leave this open til you can confirm.

**Comment by Scott-MacD** [comment]
I can confirm that the event callback appears to be working, however I'm not seeing any events in the realtime monitor in Google Analytics. I don't think that is related to this issue however.

In my first link I sent you, I had hacked a fix in to override the logic that checks which analytics solution is in use (not part of this PR) to just directly call the `gtag` function to fire the custom event instead of leaving it to the checking logic, as I was originally thinking that might have been where my issue was, that's when I discovered it wasn't being fired at all.

I'll try to look into this more later, but if you're curious here's the updated file with your latest commit:
http://thework.brandhealth.ca/metrics-test/

The events are getting fired to the dataLayer, but never sent out to Google Analytics (I'm not using Google Tag Manager, just the new default Analytics snippit)

The last version you looked at is still untouched (confirmed working)
http://thework.brandhealth.ca/

**Comment by DanWilkerson** [comment]
Ah, yes, I haven't added gtag support yet. It causes some headaches with the current (admittedly bad) syntax flagging system.

**Comment by Scott-MacD** [comment]
No worries, I think your patch is working fine for what this PR was originally intended to resolve, so I'm going to close this for now. I'll create an issue for gtag support and if I can find the time I'll try to look into it myself.

Perhaps in the meantime it's at least worth mentioning in the ReadMe.

**Comment by Scott-MacD** [comment]
Nevermind, already see an issue filed at https://github.com/lunametrics/youtube-google-analytics/issues/48

As mentioned, I'll try and find the time to take a stab at it when I can.

**Pull request closed without merging**
